name: Type Check

on:
  push:
    branches: [ main, develop ]
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/type-check.yml'
  pull_request:
    branches: [ main, develop ]
    paths:
      - 'src/**/*.py'
      - 'tests/**/*.py'
      - 'pyproject.toml'
      - '.github/workflows/type-check.yml'

jobs:
  type-check:
    name: MyPy Type Checking
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"

    - name: Install dependencies
      run: |
        uv sync

    - name: Run MyPy type checker
      run: |
        uv run mypy src/

    - name: Type check summary
      if: success()
      run: |
        echo "✅ Type checking passed successfully!"
        echo "All type annotations are valid."

    - name: Type check failure
      if: failure()
      run: |
        echo "❌ Type checking failed!"
        echo "Please fix the type errors before merging."
        exit 1
